### PR TITLE
add kopco scenario to database

### PR DESCRIPTION
**Pull request by fietew**
I uploaded the results, tools to analyse, and the figure. A skeleton for documentation is provided within this branch.

TODOs @ningma97:

- [x] add title
- [x] add description of experiment and data
- [x] add figures (describing the experimental setup and/or the results), png and pdf version appreciated
- [x] add references to own and original Kopco paper

### CODE REVIEW

**Comment by ningma97** [comment]
Could you let me know where I should add the information requested?

**Comment by fietew** [comment]
look at the changed files: https://github.com/TWOEARS/documentation/pull/45/files . There I added a new entry for the documentation.

**Comment by fietew** [comment]
@ningma97: What is the current status of this?

**Comment by ningma97** [comment]
I am working on this... Shamefully slow as took me a while to understand how to add the required information.

**Comment by ningma97** [comment]
I've added the information. Let me know if it's OK.

**Pull request merged**
