### PR TITLE
Updated BRIRs QU KEMAR Auditorium 3

### PR DESCRIPTION
**Pull request by hagenw**
I updated the description and added a new figure.

In addition I recreated the SOFA file now with MultiSpeaker convention and uploaded it to the database.
@fietew: could you please have a look at the new SOFA file and check if everything is ok. After that I will upload it to Zenodo and add the DOI in the documentation, before merging this.

### CODE REVIEW

**Comment by hagenw** [comment]
The new SOFA file can be found under `impulse_responses/qu_kemar_rooms/auditorium3/QU_KEMAR_Auditorium3.sofa` and includes all 6 sources.

**Comment by fietew** [comment]
```
clear variables

file_new = 'QU_KEMAR_Auditorium3';

meta = SOFAload([file_new '.sofa'], 'nodata');

meta_fields = {'ListenerView'
  'EmitterPosition'
  'ReceiverPosition'
  'ListenerPosition'
  };

for idx=1:size(meta.EmitterPosition,1)
  
  file_old = sprintf('%s_src%d_xs%+1.2f_ys%+1.2f.sofa', file_new, idx, ...
    meta.EmitterPosition(idx,1), meta.EmitterPosition(idx,2));
  
  irs_old = SOFAload(file_old);  
  irs_new = SOFAload([file_new '.sofa'], [idx 1], 'E');
  
  
  for kdx=1:length(meta_fields)
    fprintf(['comparing field ' meta_fields{kdx} '\n'])
    delta = irs_old.(meta_fields{kdx}) - irs_new.(meta_fields{kdx});
    disp(delta)
  end
  
  subplot(3,2,idx);
  imagesc(db(squeeze(sum((squeeze(irs_new.Data.IR(:,:,1,:)) - irs_old.Data.IR).^2, 2)), 'P'));
end
```

**Comment by fietew** [comment]
The z-coordinate of the loudspeakers is different.

Test script:

```
clear variables

file_new = 'QU_KEMAR_Auditorium3';

meta = SOFAload([file_new '.sofa'], 'nodata');

meta_fields = {'ListenerView', 'ListenerView'
  'EmitterPosition', 'SourcePosition'
  'ReceiverPosition', 'ReceiverPosition'
  'ListenerPosition', 'ListenerPosition'
  };

for idx=1:size(meta.EmitterPosition,1)

  file_old = sprintf('%s_src%d_xs%+1.2f_ys%+1.2f.sofa', file_new, idx, ...
    meta.EmitterPosition(idx,1), meta.EmitterPosition(idx,2));

  irs_old = SOFAload(file_old);  
  irs_new = SOFAload([file_new '.sofa'], [idx 1], 'E');


  for kdx=1:length(meta_fields)
    fprintf(['comparing field ' meta_fields{kdx} '\n'])
    delta = irs_old.(meta_fields{kdx,2}) - irs_new.(meta_fields{kdx,1});
    disp(delta)
  end

  figure(1);
  subplot(3,2,idx);
  imagesc(db(squeeze(sum((squeeze(irs_new.Data.IR(:,:,1,:)) - irs_old.Data.IR).^2, 2)), 'P'));

  figure(2);
  subplot(3,2,idx);
  imagesc(db(squeeze(sum(irs_new.Data.IR(:,:,1,:).^2, 2)), 'P'));
end
```

**Comment by hagenw** [comment]
Ah, that's interesting. The new height values of `1.65, 1.65, 1.60, 1.60, 1.60, 1.60` were the actual values used in the measurement. I updated them to `1.7` for the SOFA files in order to avoid problems with elevation as the listener height is also `1.7`. I would prefer to use the actual values from the measurement for the updated data set. Is this ok, or will this lead to problems with the simulator?

**Comment by hagenw** [comment]
Data is uploaded to Zenodo and DOI prereserved and added to the documentation.
If you agree on the data, we just have to click a button, otherwise I can exchange the data before publishing it.

**Comment by fietew** [comment]
> I would prefer to use the actual values from the measurement for the updated data set. Is this ok, or will this lead to problems with the simulator?

I think, this is not the criterion, we should judge apon. The goal should be to provide correct data, so using the actual data is also my preference. If the simulator can't handle it, new functionalities should be implemented. However, I think, that there shouldn't be a problem with the simulator as the brs renderer does not care about the position of the sources.

**Comment by hagenw** [comment]
OK, data is published and I'm going to merge this one.

**Pull request merged**
