### PR TITLE
add SURREY brirs

### PR DESCRIPTION
**Pull request by fietew**

### CODE REVIEW

**Comment by hagenw** [comment]
I added sketches and fixed minor things. Could you have a look at it please. Do you think we could simply remove all the references in the figure captions, or is it better to stay with the current writing?

**Comment by fietew** [comment]
Did you push the figures?

**Comment by hagenw** [comment]
Sorry, I forgot that.

**Comment by fietew** [comment]
For the layout of the figure, we can maybe use the same "table solution" as done in #20 . We could write the caption inside the table cell. I think, we could than spare some of the references.

**Comment by hagenw** [comment]
The table in #20 looks nice. I have not completely got it how to include the caption, but you can try. I will be off for today.

**Comment by hagenw** [comment]
Cool, looks good.

**Pull request merged**
