### PR TITLE
add calypso loudspeaker array brir

### PR DESCRIPTION
**Pull request by fietew**
@hagenw: Is it correct, that the measurement was done with and without the headphones on the KEMAR?

### CODE REVIEW

**Comment by hagenw** [comment]
Yes, correct. The measurement with the headphones on the KEMAR should allow for a better direct comparison between real loudspeakers and simulated with headphones on the head of the listener.

**Comment by fietew** [comment]
I think, same as for #20: merge this pull request and open a new issue for uploading the data to zenodo and adding the new DOI?

**Comment by hagenw** [comment]
I guess you mean #20. But I agree, I will create an issue for the DOI and first merge this. But before I will  merge #20, then merge the master into this one and solve the conflicts.

Interesting that the data contains only 11 loudspeakers. As far as [I can see it](https://dev.qu.tu-berlin.de/projects/capture/repository/show/data/2012-03-30_Calypso_loudspeaker_array/calypso_loudspeaker_array), [both measurements](https://dev.qu.tu-berlin.de/projects/capture/repository/show/data/2012-03-30_Calypso_loudspeaker_array/calypso_loudspeaker_array_AKGK601) contain data for all 19 loudspeakers. So, I guess we have to check what happened during the creation of the SOFA file (or is the 11 only a typo in the documentation?)

**Comment by fietew** [comment]
Is there a script available, which you used for creating the SOFA files?

The description is taken from D1.2, so I don't think, that it is a typo.

**Comment by hagenw** [comment]
The scripts are also part of the QU capture repo, see [the one without headphones](https://dev.qu.tu-berlin.de/projects/capture/repository/entry/data/2012-03-30_Calypso_loudspeaker_array/sofa/QU_KEMAR_Calypso_loudspeaker_array.m) as an example. And there it is configured `nSources = 19;`. Have you looked into the SOFA file how many loudspeakers there are?

**Comment by fietew** [comment]
Both files contain 19 entries for the Emitter<> metadata

**Comment by hagenw** [comment]
Ok, then I will simple change 11 to 19 in the description.

**Pull request merged**
