### PR TITLE
Add adream stereo images

### PR DESCRIPTION
**Pull request by fietew**
I provided a skeleton (adream-stereo.txt) for the documentation. I am currently uploading the data to the new public database.

@thomforgue, pls add the following things to the adream-stereo.txt:

- [x] select License
- [x] add a figure + caption of KEMAR with stereo cameras mounted
- [x] check, if Sketch is still valid
- [x] add general description of dataset
- [x] add short description for each type of files (raw, rect, calib)

You might want to take a look at other database entries, e.g. http://docs.twoears.eu/en/latest/database/listening-tests/quality-ratings/#listening-preference-of-different-mixes-of-one-popular-music-song-presented-by-wfs

### CODE REVIEW

**Comment by thomforgue** [comment]
Hi @fietew, I pushed the text. Could you check if it is ok?

**Comment by fietew** [comment]
@hagenw: I experience the problem, that in the html documentation subheadings like "Description", "License" occur in the left menu for this entry. I think, its due to the fact, that the "visual stimuli" structure has one level less than the other sections of the database. Is there any way to prevent that?

**Comment by hagenw** [comment]
I'm afraid I have no solution for that problem. I tried to update the heading of the title to `---` instead of `~~~` to make a larger gap to `^^^` as it is the case in the other documents, but this makes no difference on my local PC. Maybe, you can try if this is better handled on rtfd, by just merging your changes.

**Comment by fietew** [comment]
Maybe we have to use contents:: and instead of toctree:: and put all the entries in one file?

**Comment by fietew** [comment]
I tried out some option, but I does not seem to have any effect. I will merge it now and leave it as is.

**Pull request merged**
