### PR TITLE
add URO Kemar dataset

### PR DESCRIPTION
**Pull request by fietew**
@hagenw : Could you please check, if the two figures can be placed next to each other? I could not figure out, how to do that.

### CODE REVIEW

**Comment by hagenw** [comment]
You can position them next to each other, but you have to use smaller values than 50%.

But this introduces another problem, so far we always used:

``` rst
.. figure:: img/some_file.png

    Some caption
```

To place both images next to each other you have to use `image` instead of `figure`, but then no caption can be provided. So maybe we should just switch to figure and place them below each other?

**Comment by fietew** [comment]
I switched it back to two images and added the corresponding captions

**Comment by hagenw** [comment]
There is one minor point.
The doi is included as a link with the text `10.142799/depositonce-87.6`. It might be better to indicate that it is a doi. There are two easy ways:
1) Changing the text to `doi: 10.142799/depositonce-87.6`
2) Add a heading Doi, like it is done for License

Do you have a preference that works also for the zenodo dois where we have the image link?

**Comment by hagenw** [comment]
Top.

**Pull request merged**
