### PR TITLE
Stimuli section in database

### PR DESCRIPTION
**Pull request by fietew**
TODOs:

- [x] add license for noise stimuli @hagenw (i would suggest CC0)
- [x] add description about creation of noise stimuli @hagenw
- [x] delete the "binaural" stimuli
- [x] add description about instrument stimuli

### CODE REVIEW

**Comment by fietew** [comment]
@hagenw: What is the current status?

**Comment by hagenw** [comment]
I can work on Thursday on this.

**Comment by hagenw** [comment]
I added the information, please review it and merge it.

At the moment there is no license under the instruments section. Is this missing or available in another branch?

**Comment by fietew** [comment]
missing

**Pull request merged**
