### PR TITLE
Update robot intro

### PR DESCRIPTION
**Pull request by hagenw**
I updated the statement on stereo vision, that this is now available.

@thomforgue: It would be also nice if you could check the sentence at the end of the section regarding the Matlab bridge, maybe this can also be updated:
```
In later releases of |TwoEars|
we will provide you with a tutorial on how to build your own dummy head with
rotatable head, and how to use the aforementioned Matlab bridge in order to
steer its movements from within Matlab.
```

### CODE REVIEW

**Comment by hagenw** [comment]
By the way I'm talking about this section:
http://docs.twoears.eu/en/latest/intro/tutorial-robot/

**Comment by hagenw** [comment]
Maybe we can integrate here also the two links to https://github.com/TWOEARS/kemar-hardware and https://github.com/TWOEARS/low-cost-binaural-sensor?

**Comment by thomforgue** [comment]
I have added a short tutorial on how to control the head rotation from Matlab, and updated the sentence you mention in the intro.

**Comment by hagenw** [comment]
Cool, nice idea to add also an example for the head movements.

I have one question regarding the text, you write: "from MATLAB, using the matlab-genomix bridge."
For me it was not obvious where to find information about how to get the matlab-genomix-bridge. I guess you mean the package `matlab-genomix`, that is described under http://docs.twoears.eu/en/latest/robo/robo-software/installation/?highlight=matlab-genomix#install-packages-for-genom3?

Now, only the problem of the empty getting started section remains (#63). Would be nice if you could have a look at it as well.

**Comment by thomforgue** [comment]
Yes, I meant the matlab-genomix package described in the installation section. I added a reference to this section in the examples (commit 2fd087a).

About the getting started section, I propose in commit e144b6d to put introduction text at the root of the chapter and delete the getting started section. Indeed, to get started, the first section (Robotic specific software) presents general aspects of the robotic software architecture and provides installation instructions. This choice could be enhanced, but at least the chapter shows some consistency in its current state.

**Comment by hagenw** [comment]
Thanks, I will merge it.

**Pull request merged**
