### PR TITLE
Amlttp documentation

### PR DESCRIPTION
**Pull request by hagenw**

### CODE REVIEW

**Comment by hagenw** [comment]
So far the skeleton looks good.

It would look a little bit nicer in the left menu if the name would be shortened to `Training and Testing Pipeline`, but I guess this is not a good idea as `Auditory Machine Learning Training and Testing Pipeline` was already established as an official name also in your paper, wasn't it?

**Comment by kashefy** [comment]
@hagenw, we might still need to do some proof reading, but all parts are now in.

**Comment by hagenw** [comment]
Ok, perfect. We could wait with the merge until tomorrow evening, if this is enough time for proof reading.

**Comment by hagenw** [comment]
I had a first look at it.
The structure under Overview is a little bit strange. The subsection "Getting started" is on an extra page, all other subsections are on the same page as the Overview heading.

Under the section "Usage", the subsections "Select Your Labeler" and "Available label creators" can be summarized on one page. I guess the heading "Available label creators" could be simply removed.
The same holds for "Select Your Features" and "Some of the available feature creators".

**Comment by hagenw** [comment]
Any news on this?
Otherwise I would propose to merge it as it is and polish it later.

**Comment by kashefy** [comment]
Let's merge and polish later.

**Pull request merged**
