### PR TITLE
add entry for uro audiolab panorama

### PR DESCRIPTION
**Pull request by fietew**

### CODE REVIEW

**Comment by hagenw** [comment]
What is with License? At the moment it is empty.

**Comment by fietew** [comment]
I have to discuss that with Matthias

**Comment by hagenw** [comment]
Ok, I guess you haven't pushed it then to the public database. After updating the license and publishing the data I will merge this.

**Comment by fietew** [comment]
data is now available: https://dev.qu.tu-berlin.de/projects/twoears-getdata/repository/show/vision/uro_audiolab_panorama

**Comment by hagenw** [comment]
Could you please add a figure caption.

**Pull request merged**
