### PR TITLE
QU BRIRs Spirit

### PR DESCRIPTION
**Pull request by hagenw**
I pre-requested a DOI and added it to the documentation. Like in #26 I updated the SOFA file to `MultiSpeakerBRIR` and added it to the database under `impulse_responses/qu_kemar_rooms/spirit/QU_KEMAR_spirit.sofa`.
@fietew: again it would be nice if you could have a short look at it.

Before merging this, I would also like to update the sketch of the setup to be in line with our other documents. This will be a job for @chris-hld

### CODE REVIEW

**Comment by fietew** [comment]
You corrected the ListenerView to have unit length, right? 

Second (more minor) thing: the order of the Source, e.g. in EmitterPositions or EmitterView in the new dataset is now src2, src1, src3 compared to the stand-alone data from before. Maybe it is better to keep the old order. The order of the impulse responses would have to be changed accordingly.

Test script:

```
clear variables
format long

file_new = 'QU_KEMAR_spirit';

meta = SOFAload([file_new '.sofa'], 'nodata');

meta_fields = {'ListenerView', 'ListenerView'
  'EmitterPosition', 'SourcePosition'
  'ReceiverPosition', 'ReceiverPosition'
  'ListenerPosition', 'ListenerPosition'
  };

indices = [2 1 3];

for idx=1:size(meta.EmitterPosition,1)

  phi = atan2d( meta.EmitterPosition(idx,2) - meta.ListenerPosition(1,2),...
    meta.EmitterPosition(idx,1) - meta.ListenerPosition(1,1)) - 90;

  file_old = sprintf('%s_src%d_%.0fdeg.sofa', file_new, indices(idx), phi);

  irs_old = SOFAload(file_old);  
  irs_new = SOFAload([file_new '.sofa'], [idx 1], 'E');


  for kdx=1:length(meta_fields)
    fprintf(['comparing field ' meta_fields{kdx} '\n'])
    delta = irs_old.(meta_fields{kdx,2}) - irs_new.(meta_fields{kdx,1});
    disp(delta)
  end

  figure(1);
  subplot(3,2,idx);
  imagesc(db(squeeze(sum((squeeze(irs_new.Data.IR(:,:,1,:)) - irs_old.Data.IR).^2, 2)), 'P'));

  figure(2);
  subplot(3,2,idx);
  imagesc(db(squeeze(sum(irs_new.Data.IR(:,:,1,:).^2, 2)), 'P'));
end
```

**Comment by hagenw** [comment]
OK, thanks. I will have a look into this end of the week and will povide a sketch of the setup and maybe an updated data set.

**Comment by fietew** [comment]
Any updates on this?

**Comment by hagenw** [comment]
Not really. My Matlab license has to be renewed, before I can check the data again.
And today I told Chris to work on the sketch. Maybe there will be some news tomorrow.

**Comment by hagenw** [comment]
The documentation has now a nice new sketch of the actual setup.
Could you maybe perform the switch of the emitter positions as you proposed and update the data set accordingly?

**Comment by fietew** [comment]
I think, the sketch has to be adapted accordingly (switch pos 1 and 2). There is also an obsolete svg file in the commit

**Comment by fietew** [comment]
Shall I delete the other sofa files?

**Comment by fietew** [comment]
I experience the problem with the disk space again when uploading the file.

**Comment by hagenw** [comment]
I updated the documentation accordingly.
Regarding the out of space problem, I'm not sure if we can fix this in time as our admin is on parental leave at the moment.

**Comment by hagenw** [comment]
Addition: I was able to push into our internal data base, so maybe the space problem is fixed already :)

**Comment by fietew** [comment]
Yes, I works again. :-) . The data is now uploaded to the new public database

**Comment by hagenw** [comment]
OK, I have uploaded the corrected SOFA file to zenodo and will merge this now.

**Pull request merged**
