### PR TITLE
Brirs calypso surround

### PR DESCRIPTION
**Pull request by fietew**
- [x] check whether head orientation of the dataset in the internal database is allright
- [ ] check whether zenodo files  is allright

@hagenw: Is the second part, i.e. the measurement for the large loudspeaker (Genelec 8250A), also published? If not, shall I remove it from the documentation and discard it from the database?

### CODE REVIEW

**Comment by hagenw** [comment]
I think it is not yet published, but still interesting. I would propose to leave it in and I will upload it to zenodo next week.

**Comment by fietew** [comment]
Okay, is the current naming of the sub-directories allright for you? I have the impression, that the __different_positions_ could be removed.

**Comment by hagenw** [comment]
Yes, you can remove that.

**Comment by fietew** [comment]
The files on zenodo have not the same metadata as the files from the internal database. In the former, the ListenerView is different for each listening position. This should not be the case, right?

**Comment by hagenw** [comment]
Then the release at zenodo is the old incorrect data. Which is still valuable as this is the data set we really used in the experiment. For Two!Ears I would then propose that I will upload the new corrected data set to zenodo as well.

**Comment by fietew** [comment]
I would suggest to merge this pull request and open a new issue for uploading the data to zenodo and adding the new DOI.

**Comment by hagenw** [comment]
I agree.

Two things are still missing:
1) Caption for the figure/table
2) For the Adream data set we provided for the sketch in [Fig. 42](file:///home/hagen/git/twoears/twoears-documentation/_build/html-preview/database/impulse-responses/brirs.html#fig-adream-pos-setup) also the PDF file, which I think is a good idea as the original sketch is a vector graphic. Would be nice if you could add this here as well.

**Pull request merged**
