### PR TITLE
Add listening test 2016-03-01_sweet_spot

### PR DESCRIPTION
**Pull request by hagenw**
This is a first version of an entry for the listening test QoE 009 aka "finding the sweet spot".

The results is not part of the database yet nor uploaded to Zenodo.
In addition we have not clarified the license for the stimuli files, which can be downloaded here: http://www.hauptmikrofon.de/stereo-3d/orf-surround-techniques

### CODE REVIEW

**Comment by hagenw** [comment]
The data is now uploaded to the internal data base.

**Comment by fietew** [comment]
Is it correct, that the subjects chose the center position as the best one "without visual feedback"? I thought it was the other way around?

**Comment by fietew** [comment]
@spors : What is current status of the email-exchange with Helmut Wittek about licensing?
@hagenw : I will upload the data to the public database skipping the stimuli for the moment.

**Comment by hagenw** [comment]
> Is it correct, that the subjects chose the center position as the best one "without visual feedback"? I thought it was the other way around?

No it is correct as shown in Fig. #fig-2016-03-01-sweet-spot.

**Comment by hagenw** [comment]
Ok, I have prepared a zenodo entry, including everything, but also missing the stimuli at the moment.
I also pre-reserved a DOI which is now included in the documentation.

**Comment by fietew** [comment]
As there are no news about the stimuli, i would suggest that we put a link to the original data into the documentation and eventually add the stimuli afterwards.

**Comment by hagenw** [comment]
I was waiting for your/Saschas response regarding the recordings from Wittek.
If you prefer I can upload the data without the stimuli and add a link to the original DVD in the documentation.

**Comment by fietew** [comment]
> I was waiting for your/Saschas response regarding the recordings from Wittek.

Yes, I know. For the moment, I think your proposal is a good solution.

**Comment by hagenw** [comment]
OK, I have published the data set and adjusted the documentation. It should be ready for merging.

**Pull request merged**
